name: Jimflip
favicon: null
layout_spectrum: 0.24197
typography_spectrum: 0.65849
title: Welcome
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4375
  lightness: 0.6118273383472115
  saturation: 0.1003661083523184
  rhythmicContrast: 0.6060373035725206
purpose: []
