name: Jimflip
favicon: null
layout_spectrum: 0.48574
typography_spectrum: 0.74344
title: Jimflip '16
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75362715-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f4f3'
    - '#cbbfc5'
    - '#2500ac'
    - '#a17160'
    - '#407ee2'
  brandStrength: 0.3125
  lightness: 0.6118273383472115
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
